# Generated by Django 5.0.4 on 2024-05-07 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='fees',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('mobile_no', models.IntegerField()),
                ('college', models.CharField(max_length=250)),
                ('degree', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('image', models.FileField(upload_to='profile')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
            ],
        ),
    ]
